Add logic for `pdk new test` on newer PDK.

diff --git a/pdk_add_tests b/pdk_add_tests
--- a/pdk_add_tests
+++ b/pdk_add_tests
@@ -1,7 +1,5 @@
 #!/bin/bash
 
-set -e
-
 if [ ! -d manifests ] ; then
     echo 'No manifests directory found.  Exiting.' >&2
     exit 1
@@ -12,58 +10,109 @@ if [ ! -f metadata.json ] ; then
     exit 1
 fi
 
-# Look for an erb executable.
-erb=''
-erb_paths=(
-    $( type -path erb )
-    /opt/puppetlabs/puppet/bin/erb
-    /opt/puppetlabs/pdk/private/ruby/*/bin/erb
-)
+installed_pdk_version=$( pdk --version )
 
-for (( n=${#erb_paths[@]} ; n>=0 ; n-- )) ; do
-    if [ -x "${erb_paths[$n]}" ] ; then
-        erb="${erb_paths[$n]}"
-        break
-    fi
-done
-
-if [ -z "$erb" ] ; then
-    echo "Could not find erb executable.  Exiting." >&2
+if [ $? -ne 0 -o -z "$installed_pdk_version" ] ; then
+    echo "Error checking installed pdk version!" >&2
     exit 1
 fi
 
-template_url="$( jq -r '."template-url"' metadata.json )"
-template_ref="$( jq -r '."template-ref"' metadata.json )"
+vercmp () {
+    if [ "$#" -ne 2 ] ; then
+        echo "vercmp: Expected 2 arguments, got $#!" >&2
+        exit 1
+    fi
 
-case $template_url in
-    pdk-default\#*|file:*)
-        template_path=${template_url%#*}
-        if [ "$template_path" = "pdk-default" ] ; then
-            template_path=/opt/puppetlabs/pdk/share/cache/pdk-templates.git
+    a=( ${1//./ } )
+    b=( ${2//./ } )
+
+    to_test=$(( (${#a[@]} > ${#b[@]}) ? ${#a[@]} : ${#b[@]} ))
+    for (( n=0 ; n<$to_test ; n++ )) ; do
+        if [ -z "${a[$n]}" ] ; then
+            a[$n]=0
         fi
-        template_path=${template_path#file://}
-        class_spec=$( git -C "$template_path" show "$template_ref":object_templates/class_spec.erb )
-        defined_type_spec=$( git -C "$template_path" show "$template_ref":object_templates/defined_type_spec.erb )
-        ;;
+        if [ -z "${b[$n]}" ] ; then
+            b[$n]=0
+        fi
 
-    *)
-        template_dir=${template_url##*/}
-        template_dir=${template_dir%.git}
+        if [ "${a[$n]}" -lt "${b[$n]}" ] ; then
+            return 2
+        elif [ "${a[$n]}" -gt "${b[$n]}" ] ; then
+            return 0
+        fi
+    done
 
-        tmpdir="$( mktemp -d )"
+    return 1
+}
 
-        echo "Fetching templates from $template_url..." >&2
-        pushd "$tmpdir" > /dev/null
-        git clone "$template_url" --quiet
-        pushd "$template_dir" > /dev/null
-        class_spec=$( git show "$template_ref":object_templates/class_spec.erb )
-        defined_type_spec=$( git show "$template_ref":object_templates/defined_type_spec.erb )
-        popd > /dev/null
-        popd > /dev/null
+vercmp "$installed_pdk_version" 1.14.0 # `pdk new test` was added in 1.14.0
+if [ $? -le 1 ]; then
+    use_erb=0
+else
+    use_erb=1
+fi
 
-        rm -rf "$tmpdir"
-        ;;
-esac
+set -e
+
+if [ $use_erb -gt 0 ] ; then
+    if ! type jq > /dev/null ; then
+        echo "Could not find jq executable.  Exiting." >&2
+        exit 1
+    fi
+
+    # Look for an erb executable.
+    erb=''
+    erb_paths=(
+        $( type -path erb )
+        /opt/puppetlabs/puppet/bin/erb
+        /opt/puppetlabs/pdk/private/ruby/*/bin/erb
+    )
+
+    for (( n=${#erb_paths[@]} ; n>=0 ; n-- )) ; do
+        if [ -x "${erb_paths[$n]}" ] ; then
+            erb="${erb_paths[$n]}"
+            break
+        fi
+    done
+
+    if [ -z "$erb" ] ; then
+        echo "Could not find erb executable.  Exiting." >&2
+        exit 1
+    fi
+
+    template_url="$( jq -r '."template-url"' metadata.json )"
+    template_ref="$( jq -r '."template-ref"' metadata.json )"
+
+    case $template_url in
+        pdk-default\#*|file:*)
+            template_path=${template_url%#*}
+            if [ "$template_path" = "pdk-default" ] ; then
+                template_path=/opt/puppetlabs/pdk/share/cache/pdk-templates.git
+            fi
+            template_path=${template_path#file://}
+            class_spec=$( git -C "$template_path" show "$template_ref":object_templates/class_spec.erb )
+            defined_type_spec=$( git -C "$template_path" show "$template_ref":object_templates/defined_type_spec.erb )
+            ;;
+
+        *)
+            template_dir=${template_url##*/}
+            template_dir=${template_dir%.git}
+
+            tmpdir="$( mktemp -d )"
+
+            echo "Fetching templates from $template_url..." >&2
+            pushd "$tmpdir" > /dev/null
+            git clone "$template_url" --quiet
+            pushd "$template_dir" > /dev/null
+            class_spec=$( git show "$template_ref":object_templates/class_spec.erb )
+            defined_type_spec=$( git show "$template_ref":object_templates/defined_type_spec.erb )
+            popd > /dev/null
+            popd > /dev/null
+
+            rm -rf "$tmpdir"
+            ;;
+    esac
+fi
 
 for manifest in $( find manifests -name '*.pp' ) ; do
     class="$( sed -e '/^\s*class\s\+[a-z_:][a-z0-9_:]*[[:space:]({]/!d;' \
@@ -78,8 +127,12 @@ for manifest in $( find manifests -name '*.pp' ) ; do
         test=${test/%.pp/_spec.rb}
         if [ ! -f "$test" ] ; then
             echo "Creating test in $test." >&2
-            mkdir -pv "${test%/*}"
-            echo "$class_spec" | $erb "name=$class" - > "$test"
+            if [ $use_erb -gt 0 ] ; then
+                mkdir -pv "${test%/*}"
+                echo "$class_spec" | $erb "name=$class" - > "$test"
+            else
+                pdk new test -u "$class"
+            fi
         else
             echo "Found existing test in $test.  Skipping." >&2
         fi
@@ -89,8 +142,12 @@ for manifest in $( find manifests -name '*.pp' ) ; do
         test=${test/%.pp/_spec.rb}
         if [ ! -f "$test" ] ; then
             echo "Creating test in $test." >&2
-            mkdir -pv "${test%/*}"
-            echo "$defined_type_spec" | $erb "name=$define" - > "$test"
+            if [ $use_erb -gt 0 ] ; then
+                mkdir -pv "${test%/*}"
+                echo "$defined_type_spec" | $erb "name=$define" - > "$test"
+            else
+                pdk new test -u "$define"
+            fi
         else
             echo "Found existing test in $test.  Skipping." >&2
         fi
